//seerver.port=9090

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8080/realms/waisl
//spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://127.0.0.1:8080/realms/waisl/protocol/openid-connect/certs
